<page first>
On the following pages, you will type each word as accurately as possible.^^
Then you will rate how pleasant you find each of the words listed.^^
You should use the pictures to judge your ratings, and then use the keyboard to enter your rating.
</page>

<page end>
Thank you for participating in our experiment.  You will receive credit online today or tomorrow.  You may now leave.
</page>
